[package]
name = "acb"
version = "0.0.0"
edition = "2021"
rust-version = "1.77"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.4"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
time = "0.3.36"