use std::{
    path::PathBuf,
    process::{Command, Stdio},
};

use super::basic::SError;

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/node_constants.rs"));

pub fn node_available() -> bool {
    NODE_BIN_PATH.is_some()
}

pub fn run_node_script_file(
    script_path: &std::path::Path,
    args: Vec<String>,
) -> Result<String, SError> {
    let node_bin = NODE_BIN_PATH.ok_or_else(|| {
        "Node.js is not available. Install fnm (cargo install fnm) and rebuild."
            .to_string()
    })?;

    let node_modules = NODE_MODULES_PATH.ok_or_else(|| {
        "Node modules path not configured. Rebuild with fnm available.".to_string()
    })?;

    let child = Command::new(node_bin)
        .env("NODE_PATH", node_modules)
        .arg(script_path)
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;

    let output = child.wait_with_output().map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8(output.stdout).map_err(|e| e.to_string())?)
    } else {
        Err(format!(
            "Node script {} failed: {}",
            script_path.display(),
            String::from_utf8_lossy(&output.stderr)
        ))
    }
}

pub fn run_node_script(script: &str) -> Result<String, SError> {
    let node_bin = NODE_BIN_PATH.ok_or_else(|| {
        "Node.js is not available. Install fnm (cargo install fnm) and rebuild."
            .to_string()
    })?;

    let node_modules = NODE_MODULES_PATH.ok_or_else(|| {
        "Node modules path not configured. Rebuild with fnm available.".to_string()
    })?;

    let child = Command::new(node_bin)
        .env("NODE_PATH", node_modules)
        .arg("-e")
        .arg(script)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;

    let output = child.wait_with_output().map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8(output.stdout).map_err(|e| e.to_string())?)
    } else {
        Err(format!(
            "Node script execution failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
    }
}

pub fn get_node_script_dir() -> PathBuf {
    let repo_root = NODE_REPO_ROOT
        .expect("Node repo root not configured. Rebuild with fnm available.");
    PathBuf::from(repo_root).join("js")
}
