use std::{
    path::{Path, PathBuf},
    process::{Command, Stdio},
    str::FromStr,
};

use super::basic::SError;

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/venv_constants.rs"));

/// build.rs records the absolute path of the venv it created and of the source
/// tree it built from. Both have to still be there for the Python reader to
/// run, so a binary that has outlived its build tree cannot use it.
fn missing_python_env_error(missing: String) -> SError {
    format!(
        "Python PDF support is unavailable: {missing}. That path was recorded \
         when this binary was built, and nothing is there now. \
         `cargo install --git` builds in a temporary directory that cargo \
         deletes afterwards; `cargo clean` and moving the source tree have the \
         same effect. Reinstall with `cargo install --path <dir>` from a source \
         tree that will stay in place, or run the binary out of target/."
    )
}

fn python_bin() -> Result<&'static str, SError> {
    if Path::new(PYTHON_BIN_PATH).exists() {
        Ok(PYTHON_BIN_PATH)
    } else {
        Err(missing_python_env_error(format!(
            "no interpreter at {PYTHON_BIN_PATH}"
        )))
    }
}

pub fn run_python_script_file(
    script_path: &std::path::Path,
    args: Vec<String>,
) -> Result<String, SError> {
    let child = Command::new(python_bin()?)
        .arg(script_path)
        .args(args)
        // Python otherwise encodes piped stdout with the locale's code page,
        // which is not UTF-8 on Windows.
        .env("PYTHONIOENCODING", "utf-8")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;

    let output = child.wait_with_output().map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8(output.stdout).map_err(|e| e.to_string())?)
    } else {
        Err(format!(
            "Python script {} failed: {}",
            script_path.display(),
            String::from_utf8_lossy(&output.stderr)
        ))
    }
}

pub fn run_python_script(script: &str) -> Result<String, SError> {
    // Execute the Python script
    let child = Command::new(python_bin()?)
        .arg("-c")
        .arg(script)
        // Python otherwise encodes piped stdout with the locale's code page,
        // which is not UTF-8 on Windows.
        .env("PYTHONIOENCODING", "utf-8")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;

    let output = child.wait_with_output().map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8(output.stdout).map_err(|e| e.to_string())?)
    } else {
        Err(format!(
            "Python script execution failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
    }
}

pub fn get_python_script_dir() -> Result<PathBuf, SError> {
    // Path is like <repo_root>/target/{debug|release}/build/acb-xxxxxx/out/venv
    // We want to get to the repo root.
    let repo_root_path =
        PathBuf::from_str(VENV_PATH).unwrap().join("../../../../../..");
    let py_dir = repo_root_path.join("py");
    py_dir.canonicalize().map_err(|_| {
        missing_python_env_error(format!(
            "no py script directory six levels above the venv at {VENV_PATH}"
        ))
    })
}

pub fn get_python_version() -> Result<String, SError> {
    let script = r#"
import sys
print(f"Python version: {sys.version}")
print("Hello from Python!")
"#;

    match run_python_script(script) {
        Ok(output) => Ok(output),
        Err(e) => Err(e),
    }
}

#[cfg(test)]
mod tests {
    use super::run_python_script;

    /// The script itself stays ASCII so that only the output encoding is
    /// under test. `\u00e9` is representable in the Windows ANSI code page,
    /// where encoding it produces a byte that is not valid UTF-8; `\u2192`
    /// is not representable there at all, so encoding it fails outright.
    #[test]
    fn test_non_ascii_output_survives_the_pipe() {
        let output = run_python_script(r"print('caf\u00e9 \u2192')").unwrap();
        assert_eq!(output.trim_end(), "café →");
    }
}
