#!/usr/bin/env python3

import sys

class Colors:
   BLACK = "\033[0;30m"
   RED = "\033[0;31m"
   GREEN = "\033[0;32m"
   BROWN = "\033[0;33m"
   BLUE = "\033[0;34m"
   PURPLE = "\033[0;35m"
   CYAN = "\033[0;36m"
   LIGHT_GRAY = "\033[0;37m"
   DARK_GRAY = "\033[1;30m"
   LIGHT_RED = "\033[1;31m"
   LIGHT_GREEN = "\033[1;32m"
   YELLOW = "\033[1;33m"
   LIGHT_BLUE = "\033[1;34m"
   LIGHT_PURPLE = "\033[1;35m"
   LIGHT_CYAN = "\033[1;36m"
   LIGHT_WHITE = "\033[1;37m"
   BOLD = "\033[1m"
   FAINT = "\033[2m"
   ITALIC = "\033[3m"
   UNDERLINE = "\033[4m"
   BLINK = "\033[5m"
   NEGATIVE = "\033[7m"
   CROSSED = "\033[9m"
   RESET = "\033[0m"

def main():
   sell_row = False
   buy_row = False
   for line in sys.stdin.readlines():
      if "| Sell" in line:
         sell_row = True
      elif "| Buy" in line:
         buy_row = True
      elif line.startswith('+---'):
         sell_row = False
         buy_row = False

      if sell_row:
         line = Colors.BROWN + line + Colors.RESET
      elif buy_row:
         line = Colors.BLUE + line + Colors.RESET

      print(line, end='')

if __name__ == '__main__':
   main()
