.TH acb 1 "20 March 2018" "version 1.0"
.SH NAME
acb - <Description here>
.SH SYNOPSIS
Proposed layout:

acb
  [--initial-acb SYMBOL:valCURR]
  [--to-csv|-o filename]
  [--exchange-rates FILE [--exchange-rates FILE]]
  [--force-download-rates]
  [--date-fmt FORMAT]
  FILE [ FILE ... ]
.SH DESCRIPTION
TODO
.SH OPTIONS
TODO
.SH BUGS
-
.SH AUTHOR
Trevor Siemens
.SH SEE ALSO
TODO
