name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make all-notest
    - name: Run tests
      run: cargo test --verbose
