name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Rust
      run: make all-rust-notest
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: make check-rustfmt
    - name: Build WWW
      run: make www-all
